#!/bin/bash

echo "=== Checking Passkey Data in Firestore ==="
echo ""
echo "1. Checking if Firestore index is deployed..."
firebase firestore:indexes 2>&1 | grep -A 10 "security"

echo ""
echo "2. To manually check your passkey documents:"
echo "   Run: firebase firestore:read 'users/YOUR_USER_ID/security'"
echo ""
echo "3. Expected field structure:"
echo "   {"
echo "     \"authentication_method\": \"PASSKEY\","
echo "     \"isActive\": true,"
echo "     \"metadata\": {"
echo "       \"credentialId\": \"...\""
echo "     }"
echo "   }"
echo ""
echo "4. Check backend logs for:"
echo "   - '=== PASSKEY SEARCH DEBUG ==='"
echo "   - 'Query returned X documents'"
echo "   - If 0 documents, the query isn't finding anything"
echo ""
echo "5. Deploy index if needed:"
echo "   firebase deploy --only firestore:indexes"
