steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/strategiz-io/strategiz-console:latest',
      '-f', 'application-console/Dockerfile',
      '.'
    ]
images: ['gcr.io/strategiz-io/strategiz-console:latest']
