# Cloud Build configuration for strategiz-console
# Separate Cloud Run service for batch jobs (prevents interruption during API deployments)

steps:
  # Build with Maven (specific module)
  - name: 'maven:3.9.6-eclipse-temurin-21'
    args:
      - 'mvn'
      - 'clean'
      - 'package'
      - '-pl'
      - 'application-console'
      - '-am'
      - '-DskipTests'
      - '-Dmaven.javadoc.skip=true'
    env:
      - 'MAVEN_OPTS=-Xmx4g'

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/strategiz-console:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/strategiz-console:latest'
      - '-f'
      - 'application-console/Dockerfile'
      - '.'

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/strategiz-console:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/strategiz-console:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'strategiz-console'
      - '--image'
      - 'gcr.io/$PROJECT_ID/strategiz-console:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '3'
      - '--port'
      - '8080'
      - '--timeout'
      - '3600'
      - '--set-env-vars=^@^SPRING_PROFILES_ACTIVE=prod,scheduler@VAULT_ADDR=https://strategiz-vault-43628135674.us-east1.run.app@STRATEGIZ_VAULT_ADDRESS=https://strategiz-vault-43628135674.us-east1.run.app@OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp-gateway-prod-us-east-3.grafana.net/otlp@OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf@OTEL_SERVICE_NAME=strategiz-console@OTEL_RESOURCE_ATTRIBUTES=service.namespace=strategiz;deployment.environment=production;service.version=1.0.0'
      - '--set-secrets'
      - 'VAULT_TOKEN=vault-root-token:latest,GRAFANA_OTLP_AUTH_HEADER=GRAFANA_OTLP_AUTH:latest,OTEL_EXPORTER_OTLP_HEADERS=GRAFANA_OTLP_AUTH:latest'

images:
  - 'gcr.io/$PROJECT_ID/strategiz-console:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/strategiz-console:latest'

timeout: '2400s'
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
