# Optimized Cloud Build configuration
# Removes duplicate Maven build and enables Docker caching

steps:
  # Build Docker image WITH layer caching (removed --no-cache)
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--destination=gcr.io/$PROJECT_ID/strategiz-api'
      - '--cache=true'
      - '--cache-ttl=168h'  # Cache for 7 days
      - '--dockerfile=Dockerfile'
      - '--context=dir://.'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'strategiz-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/strategiz-api'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'SPRING_PROFILES_ACTIVE=prod,VAULT_ADDR=https://strategiz-vault-43628135674.us-east1.run.app,STRATEGIZ_VAULT_ADDRESS=https://strategiz-vault-43628135674.us-east1.run.app'
      - '--set-secrets'
      - 'VAULT_TOKEN=vault-root-token:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'

# Build timeout
timeout: '1800s'
