# Cloud Build configuration for strategiz-console
# Separate Cloud Run service for batch jobs (prevents interruption during API deployments)
#
# Deploy command: gcloud builds submit --config=cloudbuild-console.yaml

steps:
  # Build Docker image with Kaniko (includes Maven build inside Dockerfile)
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--destination=gcr.io/$PROJECT_ID/strategiz-console'
      - '--cache=false'
      - '--dockerfile=application-console/Dockerfile'
      - '--context=dir://.'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'strategiz-console'
      - '--image'
      - 'gcr.io/$PROJECT_ID/strategiz-console'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '4'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '3'
      - '--port'
      - '8080'
      - '--timeout'
      - '3600'
      - '--set-env-vars=^@^SPRING_PROFILES_ACTIVE=prod,scheduler@VAULT_ADDR=https://strategiz-vault-43628135674.us-east1.run.app@STRATEGIZ_VAULT_ADDRESS=https://strategiz-vault-43628135674.us-east1.run.app@OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp-gateway-prod-us-east-3.grafana.net/otlp@OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf@OTEL_SERVICE_NAME=strategiz-console@OTEL_RESOURCE_ATTRIBUTES=service.namespace=strategiz;deployment.environment=production;service.version=1.0.0'
      - '--set-secrets'
      - 'VAULT_TOKEN=vault-root-token:latest,GRAFANA_OTLP_AUTH_HEADER=GRAFANA_OTLP_AUTH:latest,OTEL_EXPORTER_OTLP_HEADERS=GRAFANA_OTLP_AUTH:latest'

timeout: '2400s'
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
