# Cloud Build configuration for Strategiz Console API
# This builds and deploys the console/batch service separately from the main API
#
# Trigger: Can be configured manually or on specific paths:
#   - application-console/**
#   - service/service-console/**
#   - batch/**
#   - business/business-marketdata/**
#
# Deploy: Cloud Run service 'strategiz-console' in us-east1

steps:
  # Step 1: Build with Maven (all modules needed for console)
  - name: 'maven:3.9.6-eclipse-temurin-21'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mvn clean install -Pdocker -Dmaven.test.skip=true \
          -Dcheckstyle.skip=true -Dspotbugs.skip=true -Dpmd.skip=true \
          -pl application-console -am && \
        rm -rf /root/.m2/repository
    timeout: 1800s

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/strategiz-console:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/strategiz-console:latest'
      - '-f'
      - 'application-console/Dockerfile'
      - '.'
    timeout: 600s

  # Step 3: Push Docker images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/strategiz-console:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/strategiz-console:latest']

  # Step 4: Deploy to Cloud Run
  # Note: Higher memory/CPU for batch jobs, min-instances=1 for always-on
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'strategiz-console'
      - '--image=gcr.io/$PROJECT_ID/strategiz-console:$COMMIT_SHA'
      - '--region=us-east1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=4Gi'
      - '--cpu=2'
      - '--min-instances=1'
      - '--max-instances=5'
      - '--concurrency=80'
      - '--timeout=3600s'
      - '--set-env-vars=SPRING_PROFILES_ACTIVE=prod,scheduler,VAULT_ADDR=https://strategiz-vault-43628135674.us-east1.run.app,STRATEGIZ_VAULT_ADDRESS=https://strategiz-vault-43628135674.us-east1.run.app'
      - '--set-secrets=VAULT_TOKEN=vault-token:latest,FIREBASE_SERVICE_ACCOUNT_KEY=firebase-service-account:latest'

images:
  - 'gcr.io/$PROJECT_ID/strategiz-console:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/strategiz-console:latest'

timeout: 2400s

options:
  machineType: 'E2_HIGHCPU_32'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY
