rootProject.name = "strategiz-core"

// Framework modules
include(":framework:framework-api-docs")
include(":framework:framework-exception")
include(":framework:framework-logging")
include(":framework:framework-secrets")

// Data modules
include(":data:data-base")
include(":data:data-auth")
include(":data:data-device")
include(":data:data-devices")
include(":data:data-exchange")
include(":data:data-portfolio")
include(":data:data-preferences")
include(":data:data-providers")
include(":data:data-session")
include(":data:data-strategy")
include(":data:data-user")
include(":data:data-watchlist")

// Client modules
include(":client:client-base")
include(":client:client-alphavantage")
include(":client:client-binanceus")
include(":client:client-coinbase")
include(":client:client-coingecko")
include(":client:client-facebook")
include(":client:client-firebase-sms")
include(":client:client-google")
include(":client:client-kraken")
include(":client:client-walletaddress")
include(":client:client-yahoo-finance")

// Business modules
include(":business:business-base")
include(":business:business-portfolio")
include(":business:business-provider-coinbase")
include(":business:business-token-auth")

// Service modules
include(":service:service-base")
include(":service:service-auth")
include(":service:service-dashboard")
include(":service:service-device")
include(":service:service-exchange")
include(":service:service-marketing")
include(":service:service-marketplace")
include(":service:service-monitoring")
include(":service:service-portfolio")
include(":service:service-profile")
include(":service:service-provider")
include(":service:service-strategy")
include(":service:service-user")
include(":service:service-walletaddress")

// Application module
include(":application")

// Configure project paths
project(":framework:framework-api-docs").projectDir = file("framework/framework-api-docs")
project(":framework:framework-exception").projectDir = file("framework/framework-exception")
project(":framework:framework-logging").projectDir = file("framework/framework-logging")
project(":framework:framework-secrets").projectDir = file("framework/framework-secrets")

project(":data:data-base").projectDir = file("data/data-base")
project(":data:data-auth").projectDir = file("data/data-auth")
project(":data:data-device").projectDir = file("data/data-device")
project(":data:data-devices").projectDir = file("data/data-devices")
project(":data:data-exchange").projectDir = file("data/data-exchange")
project(":data:data-portfolio").projectDir = file("data/data-portfolio")
project(":data:data-preferences").projectDir = file("data/data-preferences")
project(":data:data-providers").projectDir = file("data/data-providers")
project(":data:data-session").projectDir = file("data/data-session")
project(":data:data-strategy").projectDir = file("data/data-strategy")
project(":data:data-user").projectDir = file("data/data-user")
project(":data:data-watchlist").projectDir = file("data/data-watchlist")

project(":client:client-base").projectDir = file("client/client-base")
project(":client:client-alphavantage").projectDir = file("client/client-alphavantage")
project(":client:client-binanceus").projectDir = file("client/client-binanceus")
project(":client:client-coinbase").projectDir = file("client/client-coinbase")
project(":client:client-coingecko").projectDir = file("client/client-coingecko")
project(":client:client-facebook").projectDir = file("client/client-facebook")
project(":client:client-firebase-sms").projectDir = file("client/client-firebase-sms")
project(":client:client-google").projectDir = file("client/client-google")
project(":client:client-kraken").projectDir = file("client/client-kraken")
project(":client:client-walletaddress").projectDir = file("client/client-walletaddress")
project(":client:client-yahoo-finance").projectDir = file("client/client-yahoo-finance")

project(":business:business-base").projectDir = file("business/business-base")
project(":business:business-portfolio").projectDir = file("business/business-portfolio")
project(":business:business-provider-coinbase").projectDir = file("business/business-provider-coinbase")
project(":business:business-token-auth").projectDir = file("business/business-token-auth")

project(":service:service-base").projectDir = file("service/service-base")
project(":service:service-auth").projectDir = file("service/service-auth")
project(":service:service-dashboard").projectDir = file("service/service-dashboard")
project(":service:service-device").projectDir = file("service/service-device")
project(":service:service-exchange").projectDir = file("service/service-exchange")
project(":service:service-marketing").projectDir = file("service/service-marketing")
project(":service:service-marketplace").projectDir = file("service/service-marketplace")
project(":service:service-monitoring").projectDir = file("service/service-monitoring")
project(":service:service-portfolio").projectDir = file("service/service-portfolio")
project(":service:service-profile").projectDir = file("service/service-profile")
project(":service:service-provider").projectDir = file("service/service-provider")
project(":service:service-strategy").projectDir = file("service/service-strategy")
project(":service:service-user").projectDir = file("service/service-user")
project(":service:service-walletaddress").projectDir = file("service/service-walletaddress")

project(":application").projectDir = file("application")