#!/bin/bash

echo "==========================================="
echo "Firebase Phone Authentication Setup"
echo "==========================================="
echo ""
echo "Firebase provides 10,000 FREE SMS verifications per month!"
echo ""
echo "Setup Steps:"
echo ""
echo "1. Go to Firebase Console:"
echo "   https://console.firebase.google.com"
echo ""
echo "2. Create or select your project"
echo ""
echo "3. Enable Phone Authentication:"
echo "   - Go to Authentication > Sign-in method"
echo "   - Click on 'Phone' provider"
echo "   - Enable it and click 'Save'"
echo ""
echo "4. Download Service Account Credentials:"
echo "   - Go to Project Settings (gear icon)"
echo "   - Click 'Service Accounts' tab"
echo "   - Click 'Generate new private key'"
echo "   - Save the JSON file securely"
echo ""
echo "5. Set environment variables:"
echo "   export FIREBASE_CREDENTIALS_PATH=/path/to/your/service-account.json"
echo "   export FIREBASE_PROJECT_ID=your-project-id"
echo ""
echo "6. Run the application:"
echo "   FIREBASE_CREDENTIALS_PATH=/path/to/credentials.json mvn spring-boot:run -pl application"
echo ""
echo "==========================================="
echo ""

# Check if Firebase credentials are already configured
if [ ! -z "$FIREBASE_CREDENTIALS_PATH" ] && [ -f "$FIREBASE_CREDENTIALS_PATH" ]; then
    echo "✅ Firebase credentials are configured:"
    echo "   Credentials: $FIREBASE_CREDENTIALS_PATH"
    echo "   Project ID: ${FIREBASE_PROJECT_ID:-Not set}"
else
    echo "⚠️  Firebase credentials are not configured."
    echo ""
    echo "For testing without real SMS:"
    echo "The app is currently in mock mode (dev-mock-sms-enabled=true)"
    echo "OTP codes will be logged to the console for testing."
    echo ""
    echo "To enable real SMS, set up Firebase as described above."
fi