steps:
  # Build SonarQube Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sonarqube:latest'
      - '-f'
      - 'deployment/sonarqube/Dockerfile'
      - 'deployment/sonarqube'

  # Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/sonarqube:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'strategiz-sonarqube'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sonarqube:latest'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '4'
      - '--timeout'
      - '600'
      - '--max-instances'
      - '1'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'SONAR_JDBC_URL=jdbc:h2:file:/opt/sonarqube/data/sonar;NON_KEYWORDS=VALUE,SONAR_WEB_JAVAADDITIONALOPTS=-Xmx2g -Xms512m,SONAR_SEARCH_JAVAADDITIONALOPTS=-Xmx1g -Xms512m'

timeout: 1200s

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/sonarqube:latest'
