package io.strategiz.data.auth.config;

import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

/**
 * Configuration for the data-auth module.
 * Scans for components in the package structure.
 * Repository configuration is handled in data-base module.
 */
@Configuration
@ComponentScan(basePackages = "io.strategiz.data.auth")
@EnableJpaRepositories(basePackages = "io.strategiz.data.auth.repository")
public class DataAuthConfig {
    // Repository beans are auto-generated by Spring Data JPA
}
