package strategiz.service.exchange.trading.agent.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.Map;

/**
 * Represents a trading signal generated by a trading agent
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TradingSignal {
    
    /**
     * Type of trading signal
     */
    public enum SignalType {
        STRONG_BUY,
        BUY,
        NEUTRAL,
        SELL,
        STRONG_SELL
    }
    
    /**
     * Strength/confidence of the trading signal
     */
    public enum SignalStrength {
        VERY_STRONG,
        STRONG,
        MODERATE,
        WEAK
    }
    
    private String assetSymbol;             // Asset symbol (e.g., "BTC")
    private SignalType signalType;          // Type of signal (buy, sell, etc.)
    private SignalStrength strength;        // Strength/confidence of the signal
    private LocalDateTime timestamp;        // When the signal was generated
    private double currentPrice;            // Current price at signal generation
    private double targetPrice;             // Target price for the signal
    private String rationale;               // Human-readable explanation
    private String timeframe;               // Timeframe of analysis (e.g., "1d", "6h")
    private Map<String, Object> additionalMetrics; // Additional technical indicators
    
    /**
     * Get a formatted string representation of the trading signal
     * 
     * @return Formatted trading signal string
     */
    public String getFormattedSignal() {
        StringBuilder sb = new StringBuilder();
        sb.append(signalType.toString());
        
        if (strength != null) {
            sb.append(" (").append(strength.toString()).append(")");
        }
        
        sb.append(" - ").append(assetSymbol);
        sb.append(" @ $").append(String.format("%.2f", currentPrice));
        
        if (targetPrice > 0) {
            sb.append(" → Target: $").append(String.format("%.2f", targetPrice));
            
            // Calculate potential profit/loss percentage
            double pctChange = ((targetPrice - currentPrice) / currentPrice) * 100;
            sb.append(" (").append(String.format("%+.2f%%", pctChange)).append(")");
        }
        
        return sb.toString();
    }
}
