package io.strategiz.data.session.entity;

import com.google.cloud.firestore.annotation.DocumentId;
import com.google.cloud.firestore.annotation.PropertyName;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.strategiz.data.base.entity.BaseEntity;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * User session entity for Firestore storage
 * Represents an active user session with security metadata
 */
public class UserSession extends BaseEntity {

    /**
     * Unique session identifier (generated by Spring Session)
     */
    @DocumentId
    @PropertyName("sessionId")
    @JsonProperty("sessionId")
    @NotBlank
    private String sessionId;

    /**
     * ID of the authenticated user
     */
    @PropertyName("userId")
    @JsonProperty("userId")
    @NotBlank
    private String userId;

    /**
     * User's email address
     */
    @PropertyName("userEmail")
    @JsonProperty("userEmail")
    private String userEmail;

    /**
     * Session creation timestamp
     */
    @PropertyName("createdAt")
    @JsonProperty("createdAt")
    @NotNull
    private Instant createdAt;

    /**
     * Last time the session was accessed
     */
    @PropertyName("lastAccessedAt")
    @JsonProperty("lastAccessedAt")
    @NotNull
    private Instant lastAccessedAt;

    /**
     * When the session expires
     */
    @PropertyName("expiresAt")
    @JsonProperty("expiresAt")
    @NotNull
    private Instant expiresAt;

    /**
     * IP address when session was created
     */
    @PropertyName("ipAddress")
    @JsonProperty("ipAddress")
    private String ipAddress;

    /**
     * Browser user agent string
     */
    @PropertyName("userAgent")
    @JsonProperty("userAgent")
    private String userAgent;

    /**
     * Device fingerprint for security tracking
     */
    @PropertyName("deviceFingerprint")
    @JsonProperty("deviceFingerprint")
    private String deviceFingerprint;

    /**
     * Authentication Context Reference (ACR)
     * "0" = Unauthenticated, "1" = Partially authenticated, "2" = Fully authenticated
     */
    @PropertyName("acr")
    @JsonProperty("acr")
    private String acr;

    /**
     * Authenticator Assurance Level (AAL)
     * "1" = Single factor, "2" = Multi-factor, "3" = Hardware crypto (passkeys)
     */
    @PropertyName("aal")
    @JsonProperty("aal")
    private String aal;

    /**
     * Authentication Methods References
     * e.g., ["passkey", "totp", "sms"]
     */
    @PropertyName("amr")
    @JsonProperty("amr")
    private List<String> amr;

    /**
     * User roles and permissions
     */
    @PropertyName("authorities")
    @JsonProperty("authorities")
    private List<String> authorities;

    /**
     * Additional session attributes
     */
    @PropertyName("attributes")
    @JsonProperty("attributes")
    private Map<String, Object> attributes;

    /**
     * Whether this session is currently active
     */
    @PropertyName("active")
    @JsonProperty("active")
    private boolean active;

    /**
     * Reason for session termination (if not active)
     */
    @PropertyName("terminationReason")
    @JsonProperty("terminationReason")
    private String terminationReason;

    // === CONSTRUCTORS ===

    public UserSession() {
        super();
        this.active = true;
        this.createdAt = Instant.now();
        this.lastAccessedAt = Instant.now();
    }

    public UserSession(String userId) {
        super(userId);
        this.userId = userId;
        this.active = true;
        this.createdAt = Instant.now();
        this.lastAccessedAt = Instant.now();
    }

    // === REQUIRED OVERRIDES FROM BaseEntity ===

    @Override
    public String getId() {
        return sessionId;
    }

    @Override
    public void setId(String id) {
        this.sessionId = id;
    }

    @Override
    public String getCollectionName() {
        return "user_sessions";
    }

    // === SESSION VALIDATION METHODS ===

    /**
     * Check if session is expired
     */
    public boolean isExpired() {
        return expiresAt != null && Instant.now().isAfter(expiresAt);
    }

    /**
     * Check if session is valid (active and not expired)
     */
    public boolean isValid() {
        return active && !isExpired();
    }

    /**
     * Update last accessed time
     */
    public void updateLastAccessed() {
        this.lastAccessedAt = Instant.now();
    }

    /**
     * Terminate the session
     */
    public void terminate(String reason) {
        this.active = false;
        this.terminationReason = reason;
    }

    // === GETTERS AND SETTERS ===

    public String getSessionId() {
        return sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getLastAccessedAt() {
        return lastAccessedAt;
    }

    public void setLastAccessedAt(Instant lastAccessedAt) {
        this.lastAccessedAt = lastAccessedAt;
    }

    public Instant getExpiresAt() {
        return expiresAt;
    }

    public void setExpiresAt(Instant expiresAt) {
        this.expiresAt = expiresAt;
    }

    public String getIpAddress() {
        return ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    public String getUserAgent() {
        return userAgent;
    }

    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    public String getDeviceFingerprint() {
        return deviceFingerprint;
    }

    public void setDeviceFingerprint(String deviceFingerprint) {
        this.deviceFingerprint = deviceFingerprint;
    }

    public String getAcr() {
        return acr;
    }

    public void setAcr(String acr) {
        this.acr = acr;
    }

    public String getAal() {
        return aal;
    }

    public void setAal(String aal) {
        this.aal = aal;
    }

    public List<String> getAmr() {
        return amr;
    }

    public void setAmr(List<String> amr) {
        this.amr = amr;
    }

    public List<String> getAuthorities() {
        return authorities;
    }

    public void setAuthorities(List<String> authorities) {
        this.authorities = authorities;
    }

    public Map<String, Object> getAttributes() {
        return attributes;
    }

    public void setAttributes(Map<String, Object> attributes) {
        this.attributes = attributes;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public String getTerminationReason() {
        return terminationReason;
    }

    public void setTerminationReason(String terminationReason) {
        this.terminationReason = terminationReason;
    }
}