package io.strategiz.service.exchange.trading.agent.model;

import java.time.LocalDateTime;
import java.util.Map;
import java.util.Objects;

/**
 * Represents a trading signal generated by a trading agent
 */
public class TradingSignal {
    
    /**
     * Type of trading signal
     */
    public enum SignalType {
        STRONG_BUY,
        BUY,
        NEUTRAL,
        SELL,
        STRONG_SELL
    }
    
    /**
     * Strength/confidence of the trading signal
     */
    public enum SignalStrength {
        VERY_STRONG,
        STRONG,
        MODERATE,
        WEAK
    }
    
    private String assetSymbol;             // Asset symbol (e.g., "BTC")
    private SignalType signalType;          // Type of signal (buy, sell, etc.)
    private SignalStrength strength;        // Strength/confidence of the signal
    private LocalDateTime timestamp;        // When the signal was generated
    private double currentPrice;            // Current price at signal generation
    private double targetPrice;             // Target price for the signal
    private String rationale;               // Human-readable explanation
    private String timeframe;               // Timeframe of analysis (e.g., "1d", "6h")
    private Map<String, Object> additionalMetrics; // Additional technical indicators
    
    // Constructors
    public TradingSignal() {}
    
    public TradingSignal(String assetSymbol, SignalType signalType, SignalStrength strength, 
                        LocalDateTime timestamp, double currentPrice, double targetPrice, 
                        String rationale, String timeframe, Map<String, Object> additionalMetrics) {
        this.assetSymbol = assetSymbol;
        this.signalType = signalType;
        this.strength = strength;
        this.timestamp = timestamp;
        this.currentPrice = currentPrice;
        this.targetPrice = targetPrice;
        this.rationale = rationale;
        this.timeframe = timeframe;
        this.additionalMetrics = additionalMetrics;
    }
    
    // Builder pattern
    public static Builder builder() {
        return new Builder();
    }
    
    public static class Builder {
        private String assetSymbol;
        private SignalType signalType;
        private SignalStrength strength;
        private LocalDateTime timestamp;
        private double currentPrice;
        private double targetPrice;
        private String rationale;
        private String timeframe;
        private Map<String, Object> additionalMetrics;
        
        public Builder assetSymbol(String assetSymbol) {
            this.assetSymbol = assetSymbol;
            return this;
        }
        
        public Builder signalType(SignalType signalType) {
            this.signalType = signalType;
            return this;
        }
        
        public Builder strength(SignalStrength strength) {
            this.strength = strength;
            return this;
        }
        
        public Builder timestamp(LocalDateTime timestamp) {
            this.timestamp = timestamp;
            return this;
        }
        
        public Builder currentPrice(double currentPrice) {
            this.currentPrice = currentPrice;
            return this;
        }
        
        public Builder targetPrice(double targetPrice) {
            this.targetPrice = targetPrice;
            return this;
        }
        
        public Builder rationale(String rationale) {
            this.rationale = rationale;
            return this;
        }
        
        public Builder timeframe(String timeframe) {
            this.timeframe = timeframe;
            return this;
        }
        
        public Builder additionalMetrics(Map<String, Object> additionalMetrics) {
            this.additionalMetrics = additionalMetrics;
            return this;
        }
        
        public TradingSignal build() {
            return new TradingSignal(assetSymbol, signalType, strength, timestamp, 
                                   currentPrice, targetPrice, rationale, timeframe, additionalMetrics);
        }
    }
    
    // Getters and setters
    public String getAssetSymbol() { return assetSymbol; }
    public void setAssetSymbol(String assetSymbol) { this.assetSymbol = assetSymbol; }
    
    public SignalType getSignalType() { return signalType; }
    public void setSignalType(SignalType signalType) { this.signalType = signalType; }
    
    public SignalStrength getStrength() { return strength; }
    public void setStrength(SignalStrength strength) { this.strength = strength; }
    
    public LocalDateTime getTimestamp() { return timestamp; }
    public void setTimestamp(LocalDateTime timestamp) { this.timestamp = timestamp; }
    
    public double getCurrentPrice() { return currentPrice; }
    public void setCurrentPrice(double currentPrice) { this.currentPrice = currentPrice; }
    
    public double getTargetPrice() { return targetPrice; }
    public void setTargetPrice(double targetPrice) { this.targetPrice = targetPrice; }
    
    public String getRationale() { return rationale; }
    public void setRationale(String rationale) { this.rationale = rationale; }
    
    public String getTimeframe() { return timeframe; }
    public void setTimeframe(String timeframe) { this.timeframe = timeframe; }
    
    public Map<String, Object> getAdditionalMetrics() { return additionalMetrics; }
    public void setAdditionalMetrics(Map<String, Object> additionalMetrics) { this.additionalMetrics = additionalMetrics; }
    
    /**
     * Get a formatted string representation of the trading signal
     * 
     * @return Formatted trading signal string
     */
    public String getFormattedSignal() {
        StringBuilder sb = new StringBuilder();
        sb.append(signalType.toString());
        
        if (strength != null) {
            sb.append(" (").append(strength.toString()).append(")");
        }
        
        sb.append(" - ").append(assetSymbol);
        sb.append(" @ $").append(String.format("%.2f", currentPrice));
        
        if (targetPrice > 0) {
            sb.append(" → Target: $").append(String.format("%.2f", targetPrice));
            
            // Calculate potential profit/loss percentage
            double pctChange = ((targetPrice - currentPrice) / currentPrice) * 100;
            sb.append(" (").append(String.format("%+.2f%%", pctChange)).append(")");
        }
        
        return sb.toString();
    }
    
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        TradingSignal that = (TradingSignal) o;
        return Double.compare(that.currentPrice, currentPrice) == 0 &&
               Double.compare(that.targetPrice, targetPrice) == 0 &&
               Objects.equals(assetSymbol, that.assetSymbol) &&
               signalType == that.signalType &&
               strength == that.strength &&
               Objects.equals(timestamp, that.timestamp) &&
               Objects.equals(rationale, that.rationale) &&
               Objects.equals(timeframe, that.timeframe) &&
               Objects.equals(additionalMetrics, that.additionalMetrics);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(assetSymbol, signalType, strength, timestamp, currentPrice, 
                           targetPrice, rationale, timeframe, additionalMetrics);
    }
    
    @Override
    public String toString() {
        return "TradingSignal{" +
               "assetSymbol='" + assetSymbol + '\'' +
               ", signalType=" + signalType +
               ", strength=" + strength +
               ", timestamp=" + timestamp +
               ", currentPrice=" + currentPrice +
               ", targetPrice=" + targetPrice +
               ", rationale='" + rationale + '\'' +
               ", timeframe='" + timeframe + '\'' +
               ", additionalMetrics=" + additionalMetrics +
               '}';
    }
}
