package io.strategiz.client.robinhood.error;

/**
 * Error codes specific to Robinhood API client operations.
 *
 * Usage: throw new StrategizException(RobinhoodErrors.ROBINHOOD_API_ERROR);
 */
public enum RobinhoodErrors {
    ROBINHOOD_API_ERROR,
    ROBINHOOD_AUTH_FAILED,
    ROBINHOOD_INVALID_CREDENTIALS,
    ROBINHOOD_MFA_REQUIRED,
    ROBINHOOD_MFA_FAILED,
    ROBINHOOD_DEVICE_APPROVAL_REQUIRED,
    ROBINHOOD_INVALID_RESPONSE,
    ROBINHOOD_RATE_LIMIT,
    ROBINHOOD_TOKEN_EXPIRED,
    ROBINHOOD_INVALID_TOKEN,
    ROBINHOOD_NETWORK_ERROR,
    ROBINHOOD_CONFIGURATION_ERROR,
    ROBINHOOD_ACCOUNT_ERROR,
    ROBINHOOD_POSITION_ERROR,
    ROBINHOOD_CHALLENGE_EXPIRED
}
