package io.strategiz.business.historicalinsights.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Comprehensive historical insights for a symbol, generated by analyzing years of market data.
 * This class aggregates volatility, indicator effectiveness, market characteristics, and risk
 * insights to help generate data-driven trading strategies in Alpha Mode.
 */
public class SymbolInsights {

	private String symbol;

	private String timeframe;

	private int daysAnalyzed;

	// Volatility insights
	private double avgVolatility; // 14-day ATR average

	private String volatilityRegime; // LOW, MEDIUM, HIGH, EXTREME

	private double avgDailyRange; // (high - low) / close percentage

	// Top-ranked indicators (by historical effectiveness)
	@JsonProperty("topIndicators")
	private List<IndicatorRanking> topIndicators;

	// Optimal parameters discovered through grid search
	@JsonProperty("optimalParameters")
	private Map<String, Object> optimalParameters;

	// Market characteristics
	private String trendDirection; // BULLISH, BEARISH, SIDEWAYS

	private double trendStrength; // 0.0 - 1.0

	@JsonProperty("isMeanReverting")
	private boolean isMeanReverting; // Hurst exponent < 0.5

	// Risk insights
	private double avgMaxDrawdown; // Historical average maximum drawdown %

	private double avgWinRate; // Historical average win rate %

	private String recommendedRiskLevel; // LOW, MEDIUM, HIGH

	// Optional fundamentals (if requested)
	private FundamentalsInsights fundamentals;

	public SymbolInsights() {
		this.topIndicators = new ArrayList<>();
		this.optimalParameters = new HashMap<>();
	}

	// Getters and setters

	public String getSymbol() {
		return symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	public String getTimeframe() {
		return timeframe;
	}

	public void setTimeframe(String timeframe) {
		this.timeframe = timeframe;
	}

	public int getDaysAnalyzed() {
		return daysAnalyzed;
	}

	public void setDaysAnalyzed(int daysAnalyzed) {
		this.daysAnalyzed = daysAnalyzed;
	}

	public double getAvgVolatility() {
		return avgVolatility;
	}

	public void setAvgVolatility(double avgVolatility) {
		this.avgVolatility = avgVolatility;
	}

	public String getVolatilityRegime() {
		return volatilityRegime;
	}

	public void setVolatilityRegime(String volatilityRegime) {
		this.volatilityRegime = volatilityRegime;
	}

	public double getAvgDailyRange() {
		return avgDailyRange;
	}

	public void setAvgDailyRange(double avgDailyRange) {
		this.avgDailyRange = avgDailyRange;
	}

	public List<IndicatorRanking> getTopIndicators() {
		return topIndicators;
	}

	public void setTopIndicators(List<IndicatorRanking> topIndicators) {
		this.topIndicators = topIndicators;
	}

	public Map<String, Object> getOptimalParameters() {
		return optimalParameters;
	}

	public void setOptimalParameters(Map<String, Object> optimalParameters) {
		this.optimalParameters = optimalParameters;
	}

	public String getTrendDirection() {
		return trendDirection;
	}

	public void setTrendDirection(String trendDirection) {
		this.trendDirection = trendDirection;
	}

	public double getTrendStrength() {
		return trendStrength;
	}

	public void setTrendStrength(double trendStrength) {
		this.trendStrength = trendStrength;
	}

	public boolean isMeanReverting() {
		return isMeanReverting;
	}

	public void setMeanReverting(boolean meanReverting) {
		isMeanReverting = meanReverting;
	}

	public double getAvgMaxDrawdown() {
		return avgMaxDrawdown;
	}

	public void setAvgMaxDrawdown(double avgMaxDrawdown) {
		this.avgMaxDrawdown = avgMaxDrawdown;
	}

	public double getAvgWinRate() {
		return avgWinRate;
	}

	public void setAvgWinRate(double avgWinRate) {
		this.avgWinRate = avgWinRate;
	}

	public String getRecommendedRiskLevel() {
		return recommendedRiskLevel;
	}

	public void setRecommendedRiskLevel(String recommendedRiskLevel) {
		this.recommendedRiskLevel = recommendedRiskLevel;
	}

	public FundamentalsInsights getFundamentals() {
		return fundamentals;
	}

	public void setFundamentals(FundamentalsInsights fundamentals) {
		this.fundamentals = fundamentals;
	}

	/**
	 * Formats the insights into a human-readable summary suitable for AI prompt enhancement.
	 * This method is called by the AIStrategyService to inject historical context into the
	 * generation prompt.
	 * @return Formatted string with all insights
	 */
	public String toAIPromptFormat() {
		StringBuilder sb = new StringBuilder();

		sb.append(String.format("Symbol: %s | Timeframe: %s | Period: %d days (%.1f years)\n\n", symbol, timeframe,
				daysAnalyzed, daysAnalyzed / 365.25));

		// Volatility
		sb.append("VOLATILITY PROFILE:\n");
		sb.append(String.format("- Regime: %s\n", volatilityRegime));
		sb.append(String.format("- Avg ATR: $%.2f\n", avgVolatility));
		sb.append(String.format("- Avg Daily Range: %.2f%%\n\n", avgDailyRange));

		// Top indicators
		sb.append("TOP PERFORMING INDICATORS:\n");
		for (int i = 0; i < Math.min(5, topIndicators.size()); i++) {
			IndicatorRanking ranking = topIndicators.get(i);
			sb.append(String.format("%d. %s (Score: %.2f) - %s\n", i + 1, ranking.getIndicatorName(),
					ranking.getEffectivenessScore(), ranking.getReason()));
		}
		sb.append("\n");

		// Market characteristics
		sb.append("MARKET CHARACTERISTICS:\n");
		sb.append(String.format("- Trend: %s (Strength: %.0f%%)\n", trendDirection, trendStrength * 100));
		sb.append(String.format("- Type: %s\n\n", isMeanReverting ? "Mean-Reverting" : "Trending"));

		// Risk insights
		sb.append("RISK INSIGHTS:\n");
		sb.append(String.format("- Avg Win Rate: %.1f%%\n", avgWinRate));
		sb.append(String.format("- Avg Max Drawdown: %.1f%%\n", avgMaxDrawdown));
		sb.append(String.format("- Recommended Risk Level: %s\n", recommendedRiskLevel));

		return sb.toString();
	}

}
